CLOSE DATA ALL
USE DATOS\MENUS exclu
ZAP
APPEND FROM Programas\MENUS.TXT TYPE SDF
REPLACE codmenu WITH PADL( ALLTRIM( STR(RECNO())), 2, "0" ) ALL
REPLACE NomMenu WITH codmenu + " " + NomMenu ALL
BROW
