
 STORE .F. TO _TA_OT    
 STORE .F. TO _TBL_PRODU
 STORE .F. TO _TBL_PRODU
 STORE .F. TO _TBL_PRODU
 STORE .F. TO _TBL_PRODU
 STORE .F. TO _TBL_PRODU
 STORE .F. TO _TBL_PRODU
 STORE .F. TO _UT_PARAM 
 STORE .F. TO _UT_MAN   
 STORE .F. TO _UT_ACC   
 STORE .F. TO _UT_USU   
STORE .F. to _ut_sal, _ut_ade, skipvar