
 PUBLIC _TA_OT    
 PUBLIC _TBL_PRODU
 PUBLIC _TBL_PRODU
 PUBLIC _TBL_PRODU
 PUBLIC _TBL_PRODU
 PUBLIC _TBL_PRODU
 PUBLIC _TBL_PRODU
 PUBLIC _UT_PARAM 
 PUBLIC _UT_MAN   
 PUBLIC _UT_ACC   
 PUBLIC _UT_USU   
PUBLIC _UT_SAL
PUBLIC _UT_ADE
PUBLIC SKIPVAR